String manipulation 1
Boyul-Kim/c1020-code-solutions pull request #39
Opened 2020-10-18 18:23 UTC by Boyul-Kim

![image](https://user-images.githubusercontent.com/35949989/96376517-2c0db700-1134-11eb-9ee1-0aafa70a4e57.png)

2020-11-03 01:30 UTC, codingcodymiller commented on string-manipulation-1/src/is-vowel.js
> +  if (vowel[0] === charLower) {
Could you do this with a loop?

2020-11-03 01:30 UTC, codingcodymiller commented on string-manipulation-1/src/is-upper-cased.js
> +  if (falseCount > 0) {
Why the count? Can't you just return as soon as you hit a false in your loop?

2020-11-03 01:30 UTC, codingcodymiller commented on string-manipulation-1/src/is-lower-cased.js
> +  if (falseCount > 0) {
Same here, you can do this without a count 👍

2020-11-05 17:36 UTC, uzair-ashraf requested changes

2020-11-05 17:36 UTC, uzair-ashraf commented on string-manipulation-1/src/is-vowel.js
> +  }
You want to use a loop for this.

2020-11-22 22:46 UTC, thebearingedge requested changes

2020-11-22 22:46 UTC, thebearingedge commented on string-manipulation-1/src/get-words.js
> +  } else if (getWords.length > 0) {
This can just be an `else`.

2020-11-22 22:46 UTC, thebearingedge commented on string-manipulation-1/src/is-lower-cased.js
> +      falseCount++;
you can just `return false` here.

2020-11-22 22:46 UTC, thebearingedge commented on string-manipulation-1/src/is-lower-cased.js
> +  }
If your loop doesn't `return false`, you can `return true` here.

2020-11-22 22:46 UTC, thebearingedge commented on string-manipulation-1/src/is-upper-cased.js
> +  }
Same as your `isLowerCased`, a counter isn't really necessary.

2020-11-23 14:02 UTC, thebearingedge approved these changes

2020-12-03 23:02 UTC, merged