String manipulation 2
Boyul-Kim/c1020-code-solutions pull request #58
Opened 2020-10-24 18:35 UTC by Boyul-Kim

![image](https://user-images.githubusercontent.com/35949989/97090953-0168a600-15ed-11eb-8efe-b2c33e2f06dd.png)

2020-11-10 23:49 UTC, uzair-ashraf requested changes

2020-11-10 23:49 UTC, uzair-ashraf commented on string-manipulation-2/src/capitalize-word.js
> +    word = JavaScript;
how about `word = 'JavaScript'`

2020-11-10 23:49 UTC, uzair-ashraf commented on string-manipulation-2/src/capitalize-words.js
> +      var indexZero = string.slice(0, 1);
Strings are indexed.
This is the first letter
`string[0]`

2020-11-30 16:36 UTC, thebearingedge requested changes

2020-11-30 16:36 UTC, thebearingedge commented on string-manipulation-2/src/capitalize-word.js
> +    word = JavaScript;
if the word is `'javascript'`, just `return 'JavaScript'`.

2020-12-02 19:48 UTC, thebearingedge approved these changes

2020-12-03 23:01 UTC, merged