completed html-web-page - boyul kim
Boyul-Kim/c1020-code-solutions pull request #9
Opened 2020-10-06 23:54 UTC by Boyul-Kim

![image](https://user-images.githubusercontent.com/35949989/95272164-8c2b6180-07f4-11eb-8538-b7d3797a4c17.png)

2020-10-06 23:59 UTC, codingcodymiller requested changes

2020-10-06 23:59 UTC, codingcodymiller commented on html-web-page/index.html
> +  <p></p>
Is this empty `p` element being used to create space between the elements? If so, I can see the idea, but this would be incorrect. There's no need for them at the moment, you can just remove them. In the future, we will make use of `margin` to accomplish this 🤓

2020-10-06 23:59 UTC, codingcodymiller commented on html-web-page/index.html
> +    <input for="submit" type="text">
The `for` attribute is used on a `label` element, not on the input itself. You don't need a `for` attribute here, since there is no `label` 👍

2020-10-06 23:59 UTC, codingcodymiller commented on html-web-page/index.html
> +    <select name="plan" id="plan" for="submit">
The `for` attribute is used on a `label` element, not on the input itself. You don't need a `for` attribute here, since there is no `label` 👍

2020-10-07 00:04 UTC, Boyul-Kim commented
Thanks Cody! I'll take note of those for the future.

2020-10-07 00:13 UTC, codingcodymiller approved these changes

2020-10-07 00:14 UTC, merged